version: '2'
services:
    arrromania-app:
        image: arrromania
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://arrromania-postgresql:5432/arrromania
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    arrromania-postgresql:
        extends:
            file: postgresql.yml
            service: arrromania-postgresql
